#!/usr/bin/env bash
set -euo pipefail

SCRIPT_SOURCE="${BASH_SOURCE[0]}"
while [ -L "$SCRIPT_SOURCE" ]; do
  SCRIPT_DIR="$(cd -P "$(dirname "$SCRIPT_SOURCE")" && pwd)"
  SCRIPT_SOURCE="$(readlink "$SCRIPT_SOURCE")"
  case "$SCRIPT_SOURCE" in
    /*) ;;
    *) SCRIPT_SOURCE="$SCRIPT_DIR/$SCRIPT_SOURCE" ;;
  esac
done
SCRIPT_DIR="$(cd -P "$(dirname "$SCRIPT_SOURCE")" && pwd)"
REPO_ROOT="$SCRIPT_DIR"
GITHUB_ROOT="${COPILOT_WORKFLOW_GITHUB_ROOT:-$HOME/Documents/GitHub}"
BIN_DIR="${COPILOT_WORKFLOW_BIN_DIR:-$HOME/.local/bin}"
COPILOT_DIR="${COPILOT_WORKFLOW_COPILOT_DIR:-$HOME/.copilot}"

mkdir -p "$BIN_DIR" "$COPILOT_DIR"

ln -sf "$REPO_ROOT/bin/copilot-flow" "$BIN_DIR/copilot-flow"
ln -sf "$REPO_ROOT/bin/copilot-flow" "$BIN_DIR/copilot-architect"
ln -sf "$REPO_ROOT/bin/copilot-flow" "$BIN_DIR/copilot-implementer"
ln -sf "$REPO_ROOT/bin/copilot-flow" "$BIN_DIR/copilot-reviewer"

INSTRUCTIONS="$COPILOT_DIR/copilot-instructions.md"
if [ -f "$INSTRUCTIONS" ] && ! grep -q "Petr Copilot Workflow" "$INSTRUCTIONS"; then
  cp "$INSTRUCTIONS" "$INSTRUCTIONS.bak.$(date -u +%Y%m%d%H%M%S)"
fi

cat > "$INSTRUCTIONS" <<EOF
# Petr Copilot Workflow

Use Petr Copilot Workflow for three-role Copilot CLI collaboration. By default, each project's workbench is project-local:

\`<project-root>/.copilot-workflow\`

Legacy central mode is still supported when \`COPILOT_WORKFLOW_STORAGE=central\` or \`COPILOT_WORKFLOW_ROOT\` is set.

Preferred interactive role launch commands:

\`\`\`bash
copilot-architect
copilot-implementer
copilot-reviewer
\`\`\`

These are equivalent to:

\`\`\`bash
copilot-flow start architect
copilot-flow start implementer
copilot-flow start reviewer
\`\`\`

Each command starts an interactive Copilot session, automatically injects the role, and points the session at the project-local workbench.

For each project, resolve the project root with \`git rev-parse --show-toplevel\` when possible. The default project workbench is:

\`<project-root>/.copilot-workflow\`

Use these files as shared state between windows:

- \`REQUEST.md\`: user request
- \`PLAN.md\`: Architect output
- \`IMPLEMENTATION.md\`: Implementer output
- \`REVIEW.md\`: Reviewer output
- \`STATUS.md\`: first line is the current workflow status
- \`LOG.md\`: generated chronological workflow log
- \`INDEX.md\`: generated navigation index
- \`DASHBOARD.html\`: generated human-readable visual dashboard
- \`PROJECT.md\`: project metadata

Status flow:

\`\`\`text
idle -> new-request -> planning -> ready-for-implementation -> implementing -> ready-for-review -> reviewing -> approved
\`\`\`

If review finds blocking issues:

\`\`\`text
ready-for-review -> reviewing -> changes-requested -> implementing -> ready-for-review
\`\`\`

Role rules:

- Architect uses GPT-5.5, reads \`REQUEST.md\`, inspects the codebase, writes \`PLAN.md\`, and runs \`copilot-flow set-status ready-for-implementation\`. Architect must not modify project source code.
- Implementer uses Codex, reads \`REQUEST.md\`, \`PLAN.md\`, and \`REVIEW.md\` when relevant, modifies project code, writes \`IMPLEMENTATION.md\`, and runs \`copilot-flow set-status ready-for-review\`.
- Reviewer uses GPT-5.5, reads all workflow files and the current git diff, writes \`REVIEW.md\`, and runs \`copilot-flow set-status approved\` or \`copilot-flow set-status changes-requested\`. Reviewer must not modify project source code.

Do not ask the user to manually paste context between role windows. Read the workflow files instead.

Do not ask the user to manually run \`copilot-flow new\`. If the user gives a new top-level task in plain language, capture it yourself by running:

\`\`\`bash
copilot-flow new <<'REQUEST'
<full user request>
REQUEST
\`\`\`

If running the command is not appropriate, update \`REQUEST.md\` directly, reset \`PLAN.md\`, \`IMPLEMENTATION.md\`, and \`REVIEW.md\` from the workflow templates, and run \`copilot-flow set-status new-request\`.

Architect should continue directly into planning after capturing a new request. Implementer and Reviewer should capture new top-level requests and set status to \`new-request\` unless the user explicitly asks to bypass planning.

Keep Markdown files as the canonical agent-readable state. \`LOG.md\`, \`INDEX.md\`, and \`DASHBOARD.html\` are generated by \`copilot-flow\`; read them when useful, but do not edit them directly. Use \`DASHBOARD.html\` only as a generated human-readable visual artifact.

The project-local \`.copilot-workflow\` directory is intended to be visible to git. Do not write secrets, credentials, or sensitive private context into workflow files if the project will be pushed to a remote.

All three roles may be interactive. If the user gives feedback in a role window, treat it as role-specific guidance and update the relevant workflow file or project code according to that role's rules.
EOF

chmod +x "$REPO_ROOT/bin/copilot-flow"
if [ -f "$REPO_ROOT/install-skills.sh" ]; then
  chmod +x "$REPO_ROOT/install-skills.sh"
fi

printf 'Installed Petr Copilot Workflow\n'
printf 'Default workflow storage: project-local .copilot-workflow\n'
printf 'Commands linked in: %s\n' "$BIN_DIR"
